-- 코드를 입력하세요
SELECT BOARD_ID, WRITER_ID, TITLE,PRICE, 
CASE 
WHEN USED_GOODS_BOARD.STATUS = 'SALE'
THEN '판매중'
WHEN USED_GOODS_BOARD.STATUS = 'RESERVED'
THEN '예약중'
WHEN USED_GOODS_BOARD.STATUS = 'DONE'
THEN '거래완료'
END
AS STATUS
FROM USED_GOODS_BOARD 
WHERE DATE(CREATED_DATE)='2022-10-05' ORDER BY BOARD_ID DESC;